#!/usr/bin/env python3
#coding: utf8

import sys
sys.path.append("./mk")

a=28

from glink.lang.pars import parse_file as parse_file 
from glink.lang.interpret import extern_execblock as extern_execblock 
from glink.lang.interpret import seed as seed

file = open("./exampletext")

seed = 0
metablock = parse_file(file)
extern_execblock(metablock, globals())

file.close()
