#!/usr/bin/env python3
#coding: utf8

import sys
sys.path.append("./mk")

a=28

from glink.lang.pars import parse_file as parse_file 
from glink.lang.interpret import global_start 

file = open("./exampletext")

metablock = parse_file(file)
global_start(metablock, globals(), 0)

file.close()
