#!/usr/bin/env python3
#coding: utf8

import sys
sys.path.append("./mk")

a=28

from glink.lang.pars import parse_file as parse_file 
from glink.lang.interpret import extern_execblock as extern_execblock 

file = open("./exampletext")

metablock = parse_file(file)
extern_execblock(metablock, globals(), 0)

file.close()
